app:
  domain: localhost
  kind: development
  port: 8080

jwt:
  confirm_email:
    secret:
      jwt_secret: emailconfirm
    options:
      expires_in: 14hr
      issuer: poonsht
      audience: poonsht
  private_route:
    secret:
      jwt_secret: privateroute
    options:
      expires_in: 30d
      issuer: poonsht
      audience: poonsht

db:
  mongo:
    username: root
    password: root
    host: localhost
    port: 27017
    name: todo_template
    auth: admin
    collection: todo

queue:
  connection:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672