app:
  kind: production
  port: 8080

db:
  mongo:
    username: root
    password: root
    host: mongo
    port: 27017
    name: todo_template
    auth: admin
    collection: todo

queue:
  connection:
    username: guest
    password: guest
    host: rabbitmq
    port: 5672