app:
  kind: development
  port: 8080

db:
  mongo:
    username: root
    password: root
    host: 127.0.0.1
    port: 27017
    name: todo_template
    auth: admin
    collection: todo

queue:
  connection:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672